name: 'clubhouse github action'
description: "github action to control clubhouse story's workflow state"
inputs:
  config_path:
    description: "Path of config"
    required: true
    default: "./github/ch-gh.yaml"
  clubhouse_api_token:
    description: "clubhouse api token"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
