name: 'clubhouse github action'
description: "github action to control clubhouse story's workflow state"
inputs:
  github_token:
    description: "the github token"
    required: true
  pr_number:
    description: "the number of current PR"
    required: true
  shortcut_api_token:
    description: "shortcut api token"
    required: true
  pr_opened:
    description: "desired clubhouse workflow state if pr opened"
    required: true
  pr_closed:
    description: "desired clubhouse workflow state if pr closed or merged"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
